// flow-typed signature: 26601d01a299a5063cba10afbdd27c2f
// flow-typed version: <<STUB>>/bulma_v^0.7.5/flow_v0.106.3

/**
 * This is an autogenerated libdef stub for:
 *
 *   'bulma'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'bulma' {
  declare module.exports: any;
}
