// flow-typed signature: 36856885eb403f23b5ff318ab20529c3
// flow-typed version: <<STUB>>/react-spotify-web-playback_v^0.6.0/flow_v0.107.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-spotify-web-playback'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-spotify-web-playback' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-spotify-web-playback/lib/components/Actions' {
  declare module.exports: any;
}

declare module 'react-spotify-web-playback/lib/components/ClickOutside' {
  declare module.exports: any;
}

declare module 'react-spotify-web-playback/lib/components/Content' {
  declare module.exports: any;
}

declare module 'react-spotify-web-playback/lib/components/Controls' {
  declare module.exports: any;
}

declare module 'react-spotify-web-playback/lib/components/Devices' {
  declare module.exports: any;
}

declare module 'react-spotify-web-playback/lib/components/ErrorMessage' {
  declare module.exports: any;
}

declare module 'react-spotify-web-playback/lib/components/icons/Devices' {
  declare module.exports: any;
}

declare module 'react-spotify-web-playback/lib/components/icons/Favorite' {
  declare module.exports: any;
}

declare module 'react-spotify-web-playback/lib/components/icons/FavoriteOutline' {
  declare module.exports: any;
}

declare module 'react-spotify-web-playback/lib/components/icons/Next' {
  declare module.exports: any;
}

declare module 'react-spotify-web-playback/lib/components/icons/Pause' {
  declare module.exports: any;
}

declare module 'react-spotify-web-playback/lib/components/icons/Play' {
  declare module.exports: any;
}

declare module 'react-spotify-web-playback/lib/components/icons/Previous' {
  declare module.exports: any;
}

declare module 'react-spotify-web-playback/lib/components/icons/VolumeHigh' {
  declare module.exports: any;
}

declare module 'react-spotify-web-playback/lib/components/icons/VolumeLow' {
  declare module.exports: any;
}

declare module 'react-spotify-web-playback/lib/components/icons/VolumeMute' {
  declare module.exports: any;
}

declare module 'react-spotify-web-playback/lib/components/Info' {
  declare module.exports: any;
}

declare module 'react-spotify-web-playback/lib/components/Loader' {
  declare module.exports: any;
}

declare module 'react-spotify-web-playback/lib/components/Player' {
  declare module.exports: any;
}

declare module 'react-spotify-web-playback/lib/components/Slider' {
  declare module.exports: any;
}

declare module 'react-spotify-web-playback/lib/components/Volume' {
  declare module.exports: any;
}

declare module 'react-spotify-web-playback/lib' {
  declare module.exports: any;
}

declare module 'react-spotify-web-playback/lib/spotify' {
  declare module.exports: any;
}

declare module 'react-spotify-web-playback/lib/styles' {
  declare module.exports: any;
}

declare module 'react-spotify-web-playback/lib/types/common' {
  declare module.exports: any;
}

declare module 'react-spotify-web-playback/lib/types/spotify' {
  declare module.exports: any;
}

declare module 'react-spotify-web-playback/lib/utils' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-spotify-web-playback/lib/components/Actions.js' {
  declare module.exports: $Exports<'react-spotify-web-playback/lib/components/Actions'>;
}
declare module 'react-spotify-web-playback/lib/components/ClickOutside.js' {
  declare module.exports: $Exports<'react-spotify-web-playback/lib/components/ClickOutside'>;
}
declare module 'react-spotify-web-playback/lib/components/Content.js' {
  declare module.exports: $Exports<'react-spotify-web-playback/lib/components/Content'>;
}
declare module 'react-spotify-web-playback/lib/components/Controls.js' {
  declare module.exports: $Exports<'react-spotify-web-playback/lib/components/Controls'>;
}
declare module 'react-spotify-web-playback/lib/components/Devices.js' {
  declare module.exports: $Exports<'react-spotify-web-playback/lib/components/Devices'>;
}
declare module 'react-spotify-web-playback/lib/components/ErrorMessage.js' {
  declare module.exports: $Exports<'react-spotify-web-playback/lib/components/ErrorMessage'>;
}
declare module 'react-spotify-web-playback/lib/components/icons/Devices.js' {
  declare module.exports: $Exports<'react-spotify-web-playback/lib/components/icons/Devices'>;
}
declare module 'react-spotify-web-playback/lib/components/icons/Favorite.js' {
  declare module.exports: $Exports<'react-spotify-web-playback/lib/components/icons/Favorite'>;
}
declare module 'react-spotify-web-playback/lib/components/icons/FavoriteOutline.js' {
  declare module.exports: $Exports<'react-spotify-web-playback/lib/components/icons/FavoriteOutline'>;
}
declare module 'react-spotify-web-playback/lib/components/icons/Next.js' {
  declare module.exports: $Exports<'react-spotify-web-playback/lib/components/icons/Next'>;
}
declare module 'react-spotify-web-playback/lib/components/icons/Pause.js' {
  declare module.exports: $Exports<'react-spotify-web-playback/lib/components/icons/Pause'>;
}
declare module 'react-spotify-web-playback/lib/components/icons/Play.js' {
  declare module.exports: $Exports<'react-spotify-web-playback/lib/components/icons/Play'>;
}
declare module 'react-spotify-web-playback/lib/components/icons/Previous.js' {
  declare module.exports: $Exports<'react-spotify-web-playback/lib/components/icons/Previous'>;
}
declare module 'react-spotify-web-playback/lib/components/icons/VolumeHigh.js' {
  declare module.exports: $Exports<'react-spotify-web-playback/lib/components/icons/VolumeHigh'>;
}
declare module 'react-spotify-web-playback/lib/components/icons/VolumeLow.js' {
  declare module.exports: $Exports<'react-spotify-web-playback/lib/components/icons/VolumeLow'>;
}
declare module 'react-spotify-web-playback/lib/components/icons/VolumeMute.js' {
  declare module.exports: $Exports<'react-spotify-web-playback/lib/components/icons/VolumeMute'>;
}
declare module 'react-spotify-web-playback/lib/components/Info.js' {
  declare module.exports: $Exports<'react-spotify-web-playback/lib/components/Info'>;
}
declare module 'react-spotify-web-playback/lib/components/Loader.js' {
  declare module.exports: $Exports<'react-spotify-web-playback/lib/components/Loader'>;
}
declare module 'react-spotify-web-playback/lib/components/Player.js' {
  declare module.exports: $Exports<'react-spotify-web-playback/lib/components/Player'>;
}
declare module 'react-spotify-web-playback/lib/components/Slider.js' {
  declare module.exports: $Exports<'react-spotify-web-playback/lib/components/Slider'>;
}
declare module 'react-spotify-web-playback/lib/components/Volume.js' {
  declare module.exports: $Exports<'react-spotify-web-playback/lib/components/Volume'>;
}
declare module 'react-spotify-web-playback/lib/index' {
  declare module.exports: $Exports<'react-spotify-web-playback/lib'>;
}
declare module 'react-spotify-web-playback/lib/index.js' {
  declare module.exports: $Exports<'react-spotify-web-playback/lib'>;
}
declare module 'react-spotify-web-playback/lib/spotify.js' {
  declare module.exports: $Exports<'react-spotify-web-playback/lib/spotify'>;
}
declare module 'react-spotify-web-playback/lib/styles.js' {
  declare module.exports: $Exports<'react-spotify-web-playback/lib/styles'>;
}
declare module 'react-spotify-web-playback/lib/types/common.js' {
  declare module.exports: $Exports<'react-spotify-web-playback/lib/types/common'>;
}
declare module 'react-spotify-web-playback/lib/types/spotify.js' {
  declare module.exports: $Exports<'react-spotify-web-playback/lib/types/spotify'>;
}
declare module 'react-spotify-web-playback/lib/utils.js' {
  declare module.exports: $Exports<'react-spotify-web-playback/lib/utils'>;
}
